all: build run

build:
	cl /EHsc /DWIN32 /MD /I "c:\fltk" main.cpp "c:\fltk\lib\fltk.lib" ws2_32.lib comctl32.lib user32.lib gdi32.lib advapi32.lib shell32.lib ole32.lib /link /SUBSYSTEM:WINDOWS

run:
	./main
